name: browser
description: An advanced navigation system for Flutter that enables typed routes, custom transitions, and robust overlay management.
version: 0.0.1
repository: https://github.com/colosos-team/browser
homepage: https://github.com/colosos-team/browser

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  pool: ^1.5.2
  equatable: ^2.0.8
  collection: ^1.19.1

  nested: ^1.0.0
  # universal_io: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 2.1.2
  test: ^1.26.3
