name: browser_router
description: An advanced navigation system for Flutter that enables typed routes, custom transitions, and robust overlay management.
version: 0.0.3
repository: https://github.com/coolosos/browser_router
homepage: https://github.com/coolosos/browser_router
issue_tracker: https://github.com/coolosos/browser_router/issues

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  pool: ^1.5.2
  equatable: ^2.0.8
  collection: ^1.19.1

  nested: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: ^2.1.2
  test: ^1.26.3
